# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7Z3h6oKY_7iWtRKYFkic38YBOW0zUea
"""

import pandas as pd
baza={
  "FISH" :[  "Mamadaliyev Muhammadali", "Abdullayev Shahriyor", "Abduhoshimov Shahriyor", "yunusaliyev Bexruzbek", "Muhtaraliyev MUrodiljon","Mo'ydinov Ahadjon","Abdullajonov Muhammadqodir","Azimov Sardor","Xolmatov MUrodiljon","Oribjonova Mubina"  ],
  "Yoshi" :[ '19', '19', '19',  '20',  '19',  '18',  '20',  '21',  '17',  '19' ] ,
  "Maktabi" :[' 2-maktab',' 3-maktab',' 4-maktab',' 5-maktab',' 6-maktab',' 7-maktab',' 8-maktab',' 9-maktab',' 10-maktab',' 2-maktab'  ],
  "Jinsi" :[ "o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","qiz bola" ],
  "Manzili" :["Uchko'prik", "Beshariq","Andijon","Bag'dod","Qo'qon","Buvayda","Quva","Vodil","uchko'prik","Andijon" ],
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Yoshi']=="19"]
print(filtr)

filtr=db[(db['Yoshi']=="19") & (db['Manzili']=="Qo'qon")]
print(filtr)





filtr=db[db['Jinsi']=='qiz bola']
print(filtr)

filtr=db[(db['Jinsi']=="o'g'il bola")& (db['Manzili']=="Quva")]
print(filtr)

